### ISSUE TITLE
Installation issue due to missing files

### ISSUE THREAD

**Issue by abtechag** [lammps-qmdff/lammps-qmdff#1]
List of missing files:

src/accelerator_kokkos.h is missing that is referenced-included by the file src/pair.h

Makefile(s) missing in lib/python , lib/compress , lib/molfile that prevent installation of those packages

Other files may also be missing files in src/ that can prevent overall installation and lead to errors

**Comment by lammps-qmdff** [comment]
Some files were indeed missing due to gitignore policies. Added them manually for now.
